[package]
name = "util"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cuid2 = "0.1.0"
once_cell = "1.17.1"
rand = "0.8.5"
thiserror = "1.0.40"

[dev-dependencies]
pretty_assertions = "1.3.0"
